### PR TITLE
initial information (based on Verified MSISDN doc)

### PR DESCRIPTION
**Pull request by DT-DawidWroblewski**
Initial content based on Verified MSISDN docs

### CODE REVIEW

**Comment by monamok** [comment]
Thank you @DT-DawidWroblewski for the proposal.

As it was mentioned during  the meeting, Mobile Connect offers an OICD flow for authentication using SMS/OTP but the goal of CAMARA is defining APIs not having an authentication flow. 
In this case we would like to define an API that is used to verify a phone number via sending a SMS and validating the OTP.
Similar to my comment on Number Verification I think this API should focus on verifying the number as well. The authentication flow and getting the token, from our point of view should be managed outside of this API. In this case the token can be 2-legged though.

We also believe that using a general endpoint such as _/userinfo_ is not the best option (already mentioned and discussed on commonalities [issue #105](https://github.com/camaraproject/WorkingGroups/issues/105#issuecomment-1316809431)).

We suggest to have two endpoints, one to send an OTP to the phone number and another to validate the OTP. The operations can be something like this:

_POST /authentication/phone-number/send-code
{
"phone_number": "+34628649832",
"message": "{{code}} is your short code to authenticate with Cool App via SMS"
}_

And as a response we can return:
_{
"authentication_id": "ea0840f3-3663-4149-bd10-c7c6b8912105" --> unique identifier of this authentication attempt
}_

And then:

_POST /authentication/phone-number/validate-code
{
"authentication_id": "ea0840f3-3663-4149-bd10-c7c6b8912105",
"code": "AJY3"
}_

And in the response we can return 200 and the same authentication_id.
_{
"authentication_id": "ea0840f3-3663-4149-bd10-c7c6b8912105" --> unique identifier of this authentication attempt
}_


As approved [**Design Guidelines**](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md) indicate, we should include _x-correlator_ both in query and response headers. 

On the other hand, the uploaded version of API_definition is identical to Number Verification and it doesn’t include SMS+OTP specifications. But we can align the documentation once all the participants agree on the API approach.

Looking forward to receiving your feedbacks.

**Comment by monamok** [comment]
Dear all,
based on our conversation on Friday and in order to see better our proposal, I opened this [PR](https://github.com/camaraproject/NumberVerificationSMS2FA/pull/5).

**Review by DT-DawidWroblewski — COMMENTED** [review]
initial commit

**Comment by MarkusKuemmerle** [comment]
@DT-DawidWroblewski : Please contribute API definitions in the code/API_definitions/ subdirectory and not in code/API_code/. Please change this pull request in this way.

**Comment by DT-DawidWroblewski** [comment]
closing pull request -> changing API definition including name to OTP validation API

**Comment by MarkusKuemmerle** [comment]
Hello,
Sub Project is renamed now to OTPvalidationAPI.
@Jose: Would you please update the API backlog?
@Mark: Would you please update the name in Openverse?
BR, Markus

Von: DawidWroblewski ***@***.***>
Gesendet: Mittwoch, 14. Dezember 2022 16:22
An: camaraproject/NumberVerificationSMS2FA ***@***.***>
Cc: Kümmerle, Markus ***@***.***>; Comment ***@***.***>
Betreff: Re: [camaraproject/NumberVerificationSMS2FA] initial information (based on Verified MSISDN doc) (PR #2)


closing pull request -> changing API definition including name to OTP validation API

**Comment by MarkusKuemmerle** [comment]
Hi Markus

Will look at updating.

Mark

From: ***@***.*** ***@***.***>
Date: Wednesday, 14 December 2022 at 18:31
To: ***@***.*** ***@***.***>, ***@***.*** ***@***.***>
Cc: ***@***.*** ***@***.***>, Mark Cornall ***@***.***>, JOSE ANTONIO ORDOÑEZ LUCENA ***@***.***>, Wróblewski Dawid ***@***.***>
Subject: AW: [camaraproject/NumberVerificationSMS2FA] initial information (based on Verified MSISDN doc) (PR #2)
“This email has been received from an external source – please review before actioning, clicking on links, or opening attachments”

Hello,
Sub Project is renamed now to OTPvalidationAPI.
@Jose: Would you please update the API backlog?
@Mark: Would you please update the name in Openverse?
BR, Markus

Von: DawidWroblewski ***@***.***>
Gesendet: Mittwoch, 14. Dezember 2022 16:22
An: camaraproject/NumberVerificationSMS2FA ***@***.***>
Cc: Kümmerle, Markus ***@***.***>; Comment ***@***.***>
Betreff: Re: [camaraproject/NumberVerificationSMS2FA] initial information (based on Verified MSISDN doc) (PR #2)


closing pull request -> changing API definition including name to OTP validation API

**Pull request closed without merging**
